export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_DELIVERY_PRICE_SET_SELECTED_ADRESS =
  "GET_DELIVERY_PRICE_SET_SELECTED_ADRESS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_DETAILS = "GET_DETAILS";
export const POST_ORDER_ID = "POST_ORDER_ID";
export const CLEAR_DELIVERY_PRICE = "CLEAR_DELIVERY_PRICE";
export const LOADING_ORDER = "LOADING_ORDER";
